on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Create S3 bucket
        run: |
          aws s3api create-bucket --bucket was12

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://was12

      - name: Get S3 Object URL
        id: s3-url
        run: |
          echo "::set-output name=url::$(aws s3api get-object-url --bucket was12 --key index.html)"

      - name: Deploy to Web URL
        run: |
          # Use the S3 object URL to deploy the web page to a specific URL
          # Replace the `URL_TO_DEPLOY` with your specific deployment URL
          echo "Deploying to URL: ${{ steps.s3-url.outputs.url }}"
          # Additional deployment commands here using the S3 object URL and deployment URL
